### ISSUE TITLE
How to install and use this software?

### ISSUE THREAD

**Issue by eret9616** [MacEnhance/Goodbye#6]
I really need a software ,that's what goodbye describes, "quit when only 1 window left for that app",

but I don't know how to install this,

follow the readme, I installed macforge,and in "Discover", I download goodbye,

![image](https://user-images.githubusercontent.com/12445095/90601032-1d854b00-e22a-11ea-952a-3a38c89da4ed.png)

but I don't know how to make this plugin work, as I click quit button or press command+w  in textEdit, the app still running in Dock,   

I was running in 
![image](https://user-images.githubusercontent.com/12445095/90601156-545b6100-e22a-11ea-85f8-4523a6531286.png)

and SIP disabled, How to use this? help

**Comment by Wowfunhappy** [comment]
Hmm, well the first thing to see would be whether other MacForge plugins work. Have you tried any? Are they all broken or just this one?

I'm also wondering now whether this has ever been tested on Catalina. I'm running the ancient OS X Mavericks, I know @w0lfschild is on a much more reasonable version but I don't know which one.

It also might be interesting to see if [this](https://github.com/MacEnhance/Goodbye/raw/e74c37aabb2b667b111ac39bc2ef718de51ec209/Build/Goodbye.bundle.zip) older version works? Note that it _will_ close some apps when it should not, see the fix I made later on: https://github.com/MacEnhance/Goodbye/pull/5

**Comment by eret9616** [comment]
> Hmm, well the first thing to see would be whether other MacForge plugins work. Have you tried any? Are they all broken or just this one?
> 
> I'm also wondering now whether this has ever been tested on Catalina. I'm running the ancient OS X Mavericks, I know @w0lfschild is on a much more reasonable version but I don't know which one.
> 
> It also might be interesting to see if [this](https://github.com/MacEnhance/Goodbye/raw/e74c37aabb2b667b111ac39bc2ef718de51ec209/Build/Goodbye.bundle.zip) older version works? Note that it _will_ close some apps when it should not, see the fix I made later on: #5

The older version works in my mac, thank you

**Comment by Wowfunhappy** [comment]
This probably shouldn't be closed just yet—the older version has a pretty big flaw as described in that pull request! I don't have any Catalina machines though, so I'd need someone else to take a look...

**Comment by w0lfschild** [comment]
I put out an update which I think preserves the changes @Wowfunhappy made but should also work more consistently.

When `applicationShouldTerminateAfterLastWindowClosed` is triggered we should always be trying to kill the app regardless of what the apps default implementation is, so it's best to run `closeIfRightConditions` regardless.

In `closeIfRightConditions` I just made some minor adjustments, I think the line `if (sender.occlusionState & NSApplicationOcclusionStateVisible) {` may have always been returning true since NSApplicationOcclusionStateVisible is just a number

Replacing with `if (sender.occlusionState == NSApplicationOcclusionStateVisible)` should work for checking if the app has visible windows.
